application: freeotp
version: 1
runtime: python
api_version: 1

handlers:
 - url: /favicon.ico
   static_files: favicon.ico
   upload: favicon.ico

 - url: /otp
   script: oathotp.py
   secure: always

 - url: /demo
   script: oathotp.py
   secure: always

 - url: /admin
   script: oathotp.py
   secure: always

 - url: /
   static_files: template/index.html
   upload: template/index.html
   secure: optional

 - url: /.*
   script: oathotp.py
   secure: optional
