application: freeotp-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
 - url: /favicon.ico
   static_files: favicon.ico
   upload: favicon.ico

 - url: /otp
   script: oathotp.py
   secure: always

 - url: /demo
   script: oathotp.py
   secure: always

 - url: /admin
   script: oathotp.py
   secure: always

 - url: /
   static_files: template/index.html
   upload: template/index.html
   secure: optional

 - url: /.*
   script: oathotp.py
   secure: optional

libraries:
 - name: django
   version: 1.2

 - name: pycrypto
   version: 2.3
