# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Authen-HOTP
version:      0.02
version_from: lib/Authen/HOTP.pm
installdirs:  site
requires:
    Digest::HMAC:                  1
    Digest::SHA1:                  1
    Math::BigInt:                  1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
